name: tekartik_firebase_node
description: Firebase server node
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  tekartik_browser_utils:
    git: git://github.com/tekartik/browser_utils.dart
  sembast: '>=1.7.0'
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
  firebase_functions_interop: ">=1.0.0-dev.4"
  firebase_admin_interop: ">=1.0.0-dev.15.0"

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git: git://github.com/tekartik/build_utils.dart
  build_runner: ">=0.8.8"
  build_node_compilers: ">=0.1.3"
  build_test: ">=0.10.2+5"
  tekartik_firebase_test:
    path: ../firebase_test

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
#  firebase_admin_interop:
#    git: git://github.com/asaarnak/firebase-admin-interop