name: tekartik_firebase_node
description: Firebase server node
version: 0.6.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.6.0'
  firebase_functions_interop: ">=1.0.0-dev.11.0"
  firebase_admin_interop: ">=1.1.0"

dev_dependencies:
  test: ">=1.2.0"
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
  build_runner: ">=0.9.1"
  build_node_compilers: ">=0.1.8"
  build_test: ">=0.10.3"
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
  quiver_hashcode: '>=1.0.0'
#  firebase_admin_interop:
#    git: git://github.com/asaarnak/firebase-admin-interop