name: tekartik_firebase_sim_io
description: Firebase simulation
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  tekartik_firebase: any
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: packages/web_socket_io

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any

dependency_overrides:
  tekartik_firebase_test:
    path: ../firebase_test
  tekartik_firebase_sim:
    path: ../firebase_sim
  tekartik_firebase:
      path: ../firebase
  tekartik_firebase_sembast:
    path: ../firebase_sembast
