name: tekartik_firebase_persistence
description: Generic string key/value persistence (memory, file, web local storage, sdb).
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  path: ">=1.9.1"
  fs_shim: ">=2.5.2"
  idb_shim: ">=2.9.7-2"
  tekartik_browser_utils:
    git: https://github.com/tekartik/browser_utils.dart
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
    version: '>=1.1.0'

dev_dependencies:
  test: ">=1.31.0"
  web: ">=0.5.0"
  tekartik_prefs_test:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs_test
    version: '>=0.3.0'

resolution: workspace
