name: tekartik_firebase_shim_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase:
    path: ../firebase
  cloud_firestore: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

