name: tekartik_firebase_flutter
description: Firebase flutter
version: 0.7.2
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.6.0'
  firebase_core: '>=0.2.5'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run:

dependency_overrides:
  pedantic: '>=1.9.0'
  tekartik_firebase:
    path: ../firebase