name: tekartik_firebase_sim_browser
description: Firebase simulation browser client
version: 0.4.0+0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart2
    version: '>=0.4.0+0'
  tekartik_web_socket_browser:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart2
    version: '>=0.2.1'

dev_dependencies:
  test: ">=0.12.37"
  dev_test: '>=0.12.0-dev.1'
  build_runner: ">=0.9.1"
  build_web_compilers: ">=0.4.0+4"

dependency_overrides:
  tekartik_firebase_sim:
    path: ../firebase_sim
  tekartik_firebase:
    path: ../firebase