name: tekartik_firebase_sim_browser
description: Firebase simulation browser client
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.6.0

dependencies:
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart3a
    version: '>=0.6.0'
  tekartik_web_socket_browser:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart3a
    version: '>=0.2.1'

  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      ref: dart3a
      path: web_socket
dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test:
  process_run: ">=1.2.1+1"

dependency_overrides:
  tekartik_firebase_sim:
    path: ../firebase_sim
  tekartik_firebase:
    path: ../firebase
