name: tekartik_firebase_sim_browser
description: Firebase simulation browser client
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart3a
    version: '>=0.6.0'
  tekartik_web_socket_browser:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart3a
    version: '>=0.2.1'

dev_dependencies:
  dev_build:
  test: ">=0.12.37"
  build_runner: ">=0.9.1"
  build_web_compilers: ">=0.4.0+4"
  build_test:
  process_run:

dependency_overrides:
  tekartik_firebase_sim:
    path: ../firebase_sim
  tekartik_firebase:
    path: ../firebase
