name: tekartik_firebase_sim_browser
description: Firebase simulation browser client
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart2
    version: '>=0.6.0'
  tekartik_web_socket_browser:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart2
    version: '>=0.2.1'

dev_dependencies:
  dev_test:
  test: ">=0.12.37"
  build_runner: ">=0.9.1"
  build_web_compilers: ">=0.4.0+4"
  build_test:
  process_run:

dependency_overrides:
  tekartik_firebase_sim:
    path: ../firebase_sim
# Temp non nnbd
#  tekartik_firebase:
#    path: ../firebase