name: tekartik_firebase_sim_browser
description: Firebase simulation browser client
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:

  tekartik_web_socket_browser:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: packages/web_socket_browser

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  build_runner: ^0.8.7
  build_web_compilers: ^0.4.0

dependency_overrides:
  tekartik_firebase_sim:
    path: ../firebase_sim