name: tekartik_firebase_repo
description: Firebase repo (tools)
version: 0.3.6
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.5.8'
