name: tekartik_firebase_repo
description: Firebase repo (tools)
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  grinder: any
  process_run: '>=0.10.12'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.5.8'
  tekartik_firebase_rest:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_rest
      ref: dart2
  tekartik_firebase_browser:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: dart2
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2