name: _
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - firebase_local
  - firebase_test
  - firebase_sim
  - firebase
  - firebase_browser
  - firebase_sim_browser
  - firebase_sim_io
  - repo_support
