name: tekartik_firebase_sim
description: Firebase simulation
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.6.0

dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.6.0'
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart3a
    version: '>=0.2.1'
  meta: ">=1.15.0"
  synchronized: '>=1.5.0-dev.2'
  logging: any
  json_rpc_2:

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test: ">=0.10.3"
  process_run: ">=1.2.1+1"

resolution: workspace
