name: tekartik_firebase_sim
description: Firebase simulation
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.9.0

dependencies:
  cv: ">=1.1.0+4"
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.6.0'
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart3a
    version: '>=0.2.1'
  meta: ">=1.15.0"
  synchronized: '>=1.5.0-dev.2'
  logging: any
  json_rpc_2:
  tekartik_rpc:
    git:
      url: https://github.com/tekartik/rpc.dart
      ref: dart3a
      path: packages/rpc
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  fs_shim: ">=2.3.3+1"
  tekartik_app_web_socket:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_web_socket
  tekartik_web_socket_browser:
    git:
      url: https://github.com/tekartik/web_socket.dart
      ref: dart3a
      path: web_socket_browser

dev_dependencies:
  path: ">=1.9.0"
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_dev_menu
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  build_test: ">=0.10.3"
  process_run: ">=1.2.1+1"
  tekartik_firebase_test:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase_test
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase_local

resolution: workspace
