name: tekartik_firebase_sim
description: Firebase simulation
version: 0.0.2
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  tekartik_firebase:
    path: ../firebase
  tekartik_web_socket:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: packages/web_socket
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
  meta: any
  logging: any
  build_runner: ^0.8.7
  build_web_compilers: ^0.4.0

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
