name: tekartik_firebase_sim
description: Firebase simulation
version: 0.3.9
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.3.9'
  tekartik_web_socket:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart2
    version: '>=0.0.3'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  meta: any
  synchronized: '>=1.5.0-dev.2'
  logging: any
  json_rpc_2:

dev_dependencies:
  test: "^1.0.0"
  dev_test: '>=0.12.0-dev.1'
  build_runner: ">=0.9.1"
  build_web_compilers: ">=0.4.0+4"
  build_test: ">=0.10.3"

dependency_overrides:
  tekartik_firebase:
    path: ../firebase