name: tekartik_firebase_rest
description: Firebase rest
version: 0.6.2
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.6.2'
  googleapis_auth:
  googleapis:
  test: ">=1.0.0"

dev_dependencies:
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase