name: tekartik_firebase_rest
description: Firebase rest
version: 0.8.4
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.7.3'
  googleapis_auth: '>=1.4.1'
  googleapis:
  test: ">=1.0.0"
  http:
  path:
dev_dependencies:
  web: '>=0.5.0'
  dev_build:
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
  build_runner: '>=2.0.0'
  build_web_compilers: '>3.0.0'
  build_test: '>=2.0.0'
  lints: '>=1.0.0'

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
