name: tekartik_firebase_rest
description: Firebase rest
version: 0.7.5
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: null_safety
    version: '>=0.7.3'
  googleapis_auth:
  googleapis:
  test: ">=1.0.0"

dev_dependencies:
  dev_test:
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:
  tekartik_app_http:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: null_safety
      path: app_http
    version: '>=0.1.0'

dependency_overrides:
  tekartik_firebase:
    path: ../firebase