name: tekartik_firebase_rest
description: Firebase rest
version: 0.8.3
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2_3
    version: '>=0.7.3'
  googleapis_auth:
  googleapis:
  test: ">=1.0.0"
  http:
  path:
dev_dependencies:
  dev_test:
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_http
    version: '>=0.1.0'
  build_runner: '>=2.0.0'
  build_web_compilers: '>3.0.0'
  build_test: '>=2.0.0'
  lints: ^1.0.0

dependency_overrides:
  tekartik_firebase:
    path: ../firebase