name: tekartik_firebase_sembast
description: Firebase sembast
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  sembast: '>=1.9.0'
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2

dev_dependencies:
  test: any
  build_runner: ">=0.9.0"
  build_test: '>=0.10.2'
  tekartik_firebase_test:
    path: ../firebase_test

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
