name: tekartik_firebase_sembast
description: Firebase server io
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  sembast: '>=1.9.0-dev.1'
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  build_runner: ">=0.8.8"

dependency_overrides:
  tekartik_firebase_test:
    path: ../firebase_test
  tekartik_firebase:
    path: ../firebase