name: tekartik_firebase
description: Firebase core
version: 0.3.7
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.7.3'
  path: '^1.6.1'
  collection: '^1.14.10'
dev_dependencies:
  test: "^1.0.0"
  dev_test: '>=0.12.0-dev.1'
