name: tekartik_firebase
description: Firebase core
version: 0.7.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.1'
  path: '^1.6.1'
  collection: '^1.14.10'
dev_dependencies:
  test: "^1.0.0"
  build_runner:
  build_test:
  process_run: '>=0.10.12'
