name: tekartik_firebase
description: Firebase core
version: 0.9.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.1'
  path: '^1.6.1'
  collection: '^1.14.10'
  synchronized:
dev_dependencies:
  dev_test:
  test: "^1.0.0"
  build_runner:
  build_test:
  process_run: '>=0.10.12'
