name: tekartik_firebase
description: Firebase core
version: 0.9.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  collection: '>=1.14.10'
  path: '>=1.6.1'
  synchronized:
dev_dependencies:
  tekartik_firebase_test:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_test
      ref: dart3a
  dev_build:
  test: ">=1.0.0"
  build_runner:
  build_test:
  process_run: '>=0.10.12'

dependency_overrides:
  tekartik_firebase_test:
    path: ../firebase_test
