name: tekartik_firebase_node
description: Firebase server node
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  js: any
  tekartik_browser_utils:
    git: git://github.com/tekartik/browser_utils.dart
  sembast: '>=1.7.0'
  uuid: '>=1.0.0'
  tekartik_firebase:
    path: ../firebase
  firebase_functions_interop: ">=1.0.0-dev.4"
  firebase_admin_interop: ">=1.0.0-dev.10"

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  tekartik_firebase_test:
    path: ../firebase_test
  grinder: any
  tekartik_build_utils:
    git: git://github.com/tekartik/build_utils.dart
  build_runner: ">=0.8.8"
  build_node_compilers: ">=0.1.3"

dependency_overrides:
#  firebase_admin_interop:
#    git: git://github.com/tekartik/firebase-admin-interop
#    path: ../../../../../github.com/tekartik/firebase-admin-interop
#  tekartik_browser_utils:
#    path: /media/ssd/devx/git/github.com/tekartik/browser_utils.dart
