name: tekartik_firebase_browser
description: Firebase browser
version: 0.6.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  js:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.6.2'
  firebase: '>=6.0.0'
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.5.0'
  service_worker:
  googleapis_auth:

dev_dependencies:
  test: ">=0.12.37"
  http: any
  yaml: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  build_web_compilers: ">=0.4.0+4"
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.5.7'

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
  tekartik_firebase_test:
    path: ../firebase_test