name: tekartik_firebase_browser
description: Firebase browser
version: 0.8.0
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  js:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2_3
    version: '>=0.6.2'
  firebase: '>=6.0.0'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart2_3
    version: '>=0.5.0'
  tekartik_firebase_test:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_test
      ref: dart2_3
    version: '>=0.6.2'
  service_worker:
  googleapis_auth:

dev_dependencies:
  test: ">=0.12.37"
  http: any
  yaml: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  build_web_compilers: ">=0.4.0+4"
  dev_test:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
  tekartik_firebase_test:
    path: ../firebase_test