name: tekartik_firebase_browser
description: Firebase browser
version: 0.9.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  web: '>=0.5.0'
  js:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.6.2'
  firebase: '>=6.0.0'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.5.0'
  tekartik_firebase_test:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_test
      ref: dart3a
    version: '>=0.6.2'
  service_worker:
  googleapis_auth:

dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  http: any
  yaml: ">=3.1.2"
  build_runner: ">=2.4.13"
  build_test: ">=0.10.3"
  build_web_compilers: ">=4.0.11"
  dev_build: ">=1.1.2"

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
resolution: workspace
