name: tekartik_firebase_sim_io
description: Firebase simulation
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim
  tekartik_firebase_sembast:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sembast
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_io
    version: '>=0.0.2'

dev_dependencies:
  test: "^1.0.0"
  dev_test: any
  build_runner: ^0.9.0
  build_test: '>=0.10.2+5'

dependency_overrides:
  tekartik_firebase_test:
    path: ../firebase_test
  tekartik_firebase_sim:
    path: ../firebase_sim
  tekartik_firebase:
    path: ../firebase
  tekartik_firebase_sembast:
    path: ../firebase_sembast
