name: tekartik_firebase_sim_io
description: Firebase simulation
version: 0.6.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart2
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_io
      ref: dart2
    version: '>=0.2.1'

dev_dependencies:
  dev_test:
  test: "^1.0.0"
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  process_run:

dependency_overrides:
  tekartik_firebase_sim:
    path: ../firebase_sim
# temp non nnbd
#  tekartik_firebase_test:
#    path: ../firebase_test
#  tekartik_firebase:
#    path: ../firebase
#  tekartik_firebase_local:
#    path: ../firebase_local
  # tmp
  # tekartik_web_socket_io:
  #  path: ../../web_socket.dart/web_socket_io
  # tekartik_web_socket:
  #  path: ../../web_socket.dart/web_socket