name: tekartik_firebase_sim_io
description: Firebase simulation
version: 0.3.8
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_firebase_sim:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim
      ref: dart2
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_io
      ref: dart2
    version: '>=0.0.2'

dev_dependencies:
  test: "^1.0.0"
  dev_test: '>=0.12.0-dev.1'
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"

dependency_overrides:
  tekartik_firebase_test:
    path: ../firebase_test
  tekartik_firebase_sim:
    path: ../firebase_sim
  tekartik_firebase:
    path: ../firebase
  tekartik_firebase_local:
    path: ../firebase_local
