name: tekartik_firebase_local
description: Firebase local test
version: 0.9.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.4.0

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.9.0'
  path:
dev_dependencies:
  tekartik_firebase_test:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_test
      ref: dart3a
  process_run:
  build_runner:
  test:
  build_test:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase
  tekartik_firebase_test:
    path: ../firebase_test
