name: tekartik_firebase_local
description: Firebase local test
version: 0.4.0+0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.4.0+0'
  test: ">=1.0.0"

dev_dependencies:
  dev_test: '>=0.12.0-dev.1'
  tekartik_firebase_test:
    path: ../firebase_test

dependency_overrides:
  tekartik_firebase:
    path: ../firebase