name: tekartik_firebase_local
description: Firebase local test
version: 0.6.3
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.6.0'

dev_dependencies:
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:
  build_runner:
  test:
  build_test:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase