name: tekartik_firebase_local
description: Firebase local test
version: 0.9.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.14.0-0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2_3
    version: '>=0.9.0'

dev_dependencies:
  tekartik_firebase_test:
    path: ../firebase_test
  process_run:
  build_runner:
  test:
  build_test:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase