name: tekartik_firebase_local
description: Firebase local test
version: 0.9.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.7.0

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.9.0'
  path: ">=1.9.0"
dev_dependencies:
  tekartik_firebase_test:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_test
      ref: dart3a
  process_run: ">=1.2.1+1"
  build_runner: ">=2.4.13"
  test: ">=1.24.0"
  build_test:

resolution: workspace
