name: tekartik_firebase_test
description: Firebase server test
version: 0.8.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.8.0

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.6.0'
  test: ">=1.24.0"
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_dev_menu

dev_dependencies:
  process_run: ">=1.2.1+1"

resolution: workspace
