name: tekartik_firebase_test
description: Firebase server test
version: 0.6.3
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: null_safety
    version: '>=0.6.0'
  test: ">=1.0.0"

dev_dependencies:
  process_run:

dependency_overrides:
  tekartik_firebase:
    path: ../firebase