name: tekartik_firebase_test
description: Firebase server test
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase:
    path: ../firebase

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
