name: firebase_repo_support
description: Firebase repo (tools)
version: 0.3.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  path:
  pub_semver:
  process_run: '>=0.10.3'
  test:
  dev_build:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
